# One CLI to format the code tree - https://git.numtide.com/numtide/treefmt

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]

[formatter.uv]
command = "black"
includes = ["*.py"]
